POST http://localhost:3000/api/users/save-favorite
Content-Type: application/json

{
  "user": "someUserId",
  "title": "Favorite Item Title",
  "byteSize": "12345",
  "imageUrl": "http://example.com/image.jpg"
}